FROM faber-alice-demo

# Install bdd dependencies
RUN pip3 install --no-cache-dir -r Agents/requirements.behave.txt

WORKDIR ./Agents
ADD Agents/multi_ledger_config_bdd.yml ./Agents/multi_ledger_config.yml
RUN chmod a+w .
ENTRYPOINT ["behave"]
